apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: ticketing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: angelgoez/auth:latest
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: ticketing
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000