apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
  namespace: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
          env:
           - name: MONGO_INITDB_ROOT_USERNAME
             value: "authuser"
           - name: MONGO_INITDB_ROOT_PASSWORD
             value: "authpassword"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
  namespace: ticketing
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
